package com.capstone.assessmentportal.model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Category entity class.
 */

@Setter
@Getter
@NoArgsConstructor
@Entity
public class Category {
    /**
     * categoryId attribute autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long categoryId;
    /**
     * category name attribute.
     */
    private String categoryName;
    /**
     * category description attribute.
     */
    private String categoryDescription;
    /**
     * list of subcategory.
     */
    @OneToMany(mappedBy = "category", cascade = CascadeType.ALL)
    @JsonIgnore
    private List<SubCategory> subCategory = new ArrayList<>();
    /**
     * get subcategory.
     * @return subCategory
     */
    public List<SubCategory> getSubCategory() {
        return new ArrayList<>(subCategory);
    }
    /**
     * set subcategory.
     * @param subcategory subcategory
     */
    public void setSubCategory(final List<SubCategory> subcategory) {
        this.subCategory = new ArrayList<>(subcategory);
    }
    /**
     * parameter constructor for category.
     * @param categoryid categoryid
     * @param categoryname categoryname
     * @param categorydescription categorydescription
     */
    public Category(final Long categoryid,
            final String categoryname,
            final String categorydescription) {
        this.categoryId = categoryid;
        this.categoryName = categoryname;
        this.categoryDescription = categorydescription;
    }
}
