package com.capstone.assessmentportal.model;

import com.capstone.assessmentportal.dto.Gender;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * users entity class.
 */
@Setter
@Getter
@NoArgsConstructor
@Entity
public class Users {
    /**
     * user id autogenerated attribute.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long userId;
    /**
     * first name of user attribute.
     */
    private String firstName;
    /**
     * last name of user attribute.
     */
    private String lastName;
    /**
     * date of birth(dd-mm-yyyy) attribute.
     */
    private String dateOfBirth;
    /**
     * user gender attribute.
     */
    @Enumerated(EnumType.STRING)
    private Gender gender;
    /**
     * user email attribute.
     */
    private String emailId;
    /**
     * user password attribute.
     */
    private String password;
    /**
     * role of user attribute.
     */
    private String userType = "Student";
    /**
     * parameter constructor for users.
     * @param userid userid
     * @param firstname firstname
     * @param lastname lastname
     * @param dateofBirth dateofBirth
     * @param genDer genDer
     * @param emailid emailid
     */
    public Users(final Long userid, final String firstname,
            final String lastname, final String dateofBirth,
            final Gender genDer, final String emailid) {
        this.userId = userid;
        this.firstName = firstname;
        this.lastName = lastname;
        this.dateOfBirth = dateofBirth;
        this.gender = genDer;
        this.emailId = emailid;
    }
}
