package com.capstone.assessmentPortal.dto;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

/**
 *category dto class.
*/

@Data
public class CategoryDetailsDto {
  /**
   *categoryId attribute autogenerated.
  */
  @Id
  private Long categoryId;
  /**
   *category name attribute.
  */
  @Column(unique = true)
  @NotEmpty(message = "Category Name is required")
  private String categoryName;
  /**
   *category description attribute.
  */
  @Column(nullable = true)
  private String categoryDescription;
}
