package com.capstone.assessmentPortal.dto;

import com.capstone.assessmentPortal.response.ValidationMessage;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
/**
 * Questions dto class.
 */
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class QuestionDto {
    /**
     * question id attribute autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long questionId;
    /**
     * question title attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.questionNotblank)
    private String questionContent;
    /**
     * question option 1 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.optionANotblank)
    private String optionA;
    /**
     * question option 2 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.optionBNotblank)
    private String optionB;
    /**
     * question option 3 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.optionCNotblank)
    private String optionC;
    /**
     * question option 4 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.optionDNotblank)
    private String optionD;
    /**
     * question answer attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.correctAnswerNotblank)
    private String correctAnswer;
    /**
     * subCategory id attribute.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.quizIdNotnull)
    private Long subCategoryId;
}
