package com.capstone.assessmentPortal.dto;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import com.capstone.assessmentPortal.response.ValidationMessage;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * result id attribute autogenerated.
 */
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
public class ResultsDto {
    /**
     * result id attribute autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long resultId;
    /**
     * student id from users table.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.studentIdNotnull)
    private Long studentId;
    /**
     * subcategory Id from subCategory table.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.quizIdNotnull)
    private Long subCategoryId;
    /**
     * category Id from category table.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.categoryIdNotnull)
    private Long categoryId;
    /**
     * marks obtained in quiz attribute.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.marksObtainedNotnull)
    private int marksObtained;
    /**
     * total marks of quiz attribute.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.totalMarksNotnull)
    private int totalMarks;
    /**
     * number of questions attempted attribute.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.attemptedQuestionsNotnull)
    private int numOfAttemptedQuestions;
    /**
     * total questions in quiz attribute.
     */
    @Column(nullable = false)
    @NotNull(message = ValidationMessage.totalQuestionsNotnull)
    private int totalQuestions;
    /**
     * date and time of quiz attempted attribute.
     */
    @Column(nullable = false)
    private String dateAndTime;
    /**
     * set date and time.
     * @return dateandtime
     */
    public final String setDateAndTimeMethod() {
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter
                .ofPattern("yyyy-MM-dd HH:mm:ss");
        return currentDateTime.format(formatter);
    }
}
