package com.capstone.assessmentPortal.dto;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

/**
 *subcategory dto class.
*/

@Setter
@Getter
public class SubCategoryDetailsDto {
    /**
     * subcategory id autogenerated attribute.
    */
   @Id
   @GeneratedValue(strategy = GenerationType.AUTO)
   private Long subCategoryId;
  /**
   *subcategory name attribute.
  */
  @Column(nullable = false)
  @NotBlank(message = "Quiz Name is required")
  private String subCategoryName;
  /**
   *subcategory description attribute.
  */
  private String subCategoryDescription;
  /**
   *subcategory time limit in minutes for quiz attribute.
  */
  @Column(nullable = false)
  @NotBlank(message = "Time Limit is required")
  private String timeLimitInMinutes;
  /**
   *category Id attribute.
  */
  @Column(nullable = false)
  @NotBlank(message = "Category Id is required")
  private Long categoryId;
}
