package com.capstone.assessmentPortal.dto;

import com.capstone.assessmentPortal.response.ValidationMessage;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

/**
 *subcategory dto class.
*/

@Setter
@Getter
public class SubCategoryDetailsDto {
    /**
     * subcategory id autogenerated attribute.
    */
   @Id
   @GeneratedValue(strategy = GenerationType.AUTO)
   private Long subCategoryId;
  /**
   *subcategory name attribute.
  */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.quizNameNotblank)
  private String subCategoryName;
  /**
   *subcategory description attribute.
  */
  private String subCategoryDescription;
  /**
   *subcategory time limit in minutes for quiz attribute.
  */
  @Column(nullable = false)
  @NotEmpty(message = ValidationMessage.timeLimitNotblank)
  private String timeLimitInMinutes;
  /**
   *category Id attribute.
  */
  @Column(nullable = false)
  @NotNull(message = ValidationMessage.categoryIdNotnull)
  private Long categoryId;
}
