package com.capstone.assessmentPortal.dto;

import com.capstone.assessmentPortal.response.ValidationMessage;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;

/**
 * users Dto class for getting user details.
*/

@Setter
@Getter
public class UserDetails {
  /**
   * user id autogenerated attribute.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long userId;
  /**
   *first name of user attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.firstNameNotblank)
  private String firstName;
  /**
   *last name of user attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.lastNameNotblank)
  private String lastName;
  /**
   *date of birth(dd-mm-yyyy) attribute.
 */
  @Column(nullable = false)
  @Pattern(regexp = "\\d{2}-\\d{2}-\\d{4}",
         message = ValidationMessage.dobPattern)
  @NotBlank(message = ValidationMessage.dobNotblank)
  private String dateOfBirth;
  /**
   *user gender attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.genderNotblank)
  private String gender;
  /**
   *user email attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.emailNotblank)
  @Pattern(regexp = "^[A-Z0-9a-z.+_-]+@nucleusteq[.]com$",
          message = ValidationMessage.emailPattern)
  private String emailId;
  /**
   *role of user attribute.
 */
  private String userType = "Student";
}
