package com.capstone.assessmentPortal.dto;

import com.capstone.assessmentPortal.response.ValidationMessage;
import com.fasterxml.jackson.annotation.JsonInclude;

import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.Setter;

/**
 * users Dto class for getting user details.
*/

@Setter
@Getter
@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserDetails {
  /**
   * user id autogenerated attribute.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long userId;
  /**
   *first name of user attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.FIRSTNAME_NOTBLANK)
  private String firstName;
  /**
   *last name of user attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.LASTNAME_NOTBLANK)
  private String lastName;
  /**
   *date of birth(dd-mm-yyyy) attribute.
 */
  @Column(nullable = false)
  @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}",
         message = ValidationMessage.DOB_PATTERN)
  @NotBlank(message = ValidationMessage.DOB_NOTBLANK)
  private String dateOfBirth;
  /**
   *user gender attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.GENDER_NOTBLANK)
  private String gender;
  /**
   *user email attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.EMAIL_NOTBLANK)
  @Pattern(regexp = "^[A-Z0-9a-z.+_-]+@nucleusteq[.]com$",
          message = ValidationMessage.EMAIL_PATTERN)
  private String emailId;
  /**
   *role of user attribute.
 */
  private String userType = "Student";
}
