package com.capstone.assessmentPortal.model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotEmpty;
import lombok.Data;

/**
 * Category entity class.
*/

@Data
@Entity
public class Category {
  /**
   *categoryId attribute autogenerated.
  */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long categoryId;
  /**
   *category name attribute.
  */
  @Column(unique = true)
  @NotEmpty(message = "Category Name is required")
  private String categoryName;
  /**
   *category description attribute.
  */
  @Column(nullable = true)
  private String categoryDescription;
  /**
   *list of subcategory.
  */
  @OneToMany(mappedBy = "category", cascade = CascadeType.ALL)
  @JsonIgnore
  private List<SubCategory> subCategory = new ArrayList<>();
}
