package com.capstone.assessmentPortal.model;

import com.capstone.assessmentPortal.response.ValidationMessage;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Questions of quiz entity class.
 */

@Setter
@Getter
@NoArgsConstructor
@Entity
public class Question {
    /**
     * question id attribute autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long questionId;
    /**
     * question title attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.QUESTION_NOTBLANK)
    private String questionContent;
    /**
     * question option 1 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.OPTIONA_NOTBLANK)
    private String optionA;
    /**
     * question option 2 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.OPTIONB_NOTBLANK)
    private String optionB;
    /**
     * question option 3 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.OPTIONC_NOTBLANK)
    private String optionC;
    /**
     * question option 4 attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.OPTIOND_NOTBLANK)
    private String optionD;
    /**
     * question answer attribute.
     */
    @Column(nullable = false)
    @NotBlank(message = ValidationMessage.CORRECTANSWER_NOTBLANK)
    private String correctAnswer;
    /**
     * foreign key attribute of subcategory.
     */
    @ManyToOne
    @JoinColumn(name = "subCategoryId")
    private SubCategory subCategory;
    /**
     * get subcategory.
     * @return subCategory
     */
    public final SubCategory getSubCategory() {
        return new SubCategory(subCategory.getSubCategoryId(),
                subCategory.getSubCategoryName(),
                subCategory.getSubCategoryDescription(),
                subCategory.getTimeLimitInMinutes());
    }
    /**
     * set subCategory.
     * @param subcategory subcategory
     */
    public final void setSubCategory(final SubCategory subcategory) {
        this.subCategory = new SubCategory(subcategory.getSubCategoryId(),
                subcategory.getSubCategoryName(),
                subcategory.getSubCategoryDescription(),
                subcategory.getTimeLimitInMinutes());
    }
    /**
     * parameter constructor for question.
     * @param questioncontent questioncontent
     * @param optiona optiona
     * @param optionb optionb
     * @param optionc optionc
     * @param optiond optiond
     * @param correctAns correctAns
     */
    public Question(final String questioncontent, final String optiona,
            final String optionb, final String optionc, final String optiond,
            final String correctAns) {
        this.questionContent = questioncontent;
        this.optionA = optiona;
        this.optionB = optionb;
        this.optionC = optionc;
        this.optionD = optiond;
        this.correctAnswer = correctAns;
    }
}
