package com.capstone.assessmentPortal.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.Data;

/**
 * Questions of quiz entity class.
*/

@Data
@Entity
public class Question {
  /**
   *question id attribute autogenerated.
  */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long questionId;
  /**
   *question title attribute.
  */
  @Column(nullable = false)
  private String questionContent;
  /**
   *question option 1 attribute.
  */
  @Column(nullable = false)
  private String optionA;
  /**
   *question option 2 attribute.
  */
  @Column(nullable = false)
  private String optionB;
  /**
   * question option 3 attribute.
  */
  @Column(nullable = false)
  private String optionC;
  /**
   *question option 4 attribute.
  */
  @Column(nullable = false)
  private String optionD;
  /**
   *question answer attribute.
  */
  @Column(nullable = false)
  private String correctAnswer;
  /**
   *foreign key attribute of subcategory.
  */
  @ManyToOne
  @JoinColumn(name = "subCategoryId")
  private SubCategory subCategory;
}
