package com.capstone.assessmentPortal.model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotEmpty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Subcategory entity class.
*/

@ToString
@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity
public class SubCategory {
  /**
   *subcategory id autogenerated attribute.
  */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long subCategoryId;
  /**
   *subcategory name attribute.
  */
  @Column(nullable = false)
  private String subCategoryName;
  /**
   *subcategory description attribute.
  */
  @Column(nullable = true)
  private String subCategoryDescription;
  /**
   *subcategory time limit in minutes for quiz attribute.
  */
  @Column
  @NotEmpty(message = "Time limit should not be empty")
  private String timeLimitInMinutes;
  /**
   *status of quiz attempted by user or not attribute.
  */
  @Column
  private boolean isAttempted = false;
  /**
   *category entity class reference variable attribute.
  */
  @ManyToOne
  @JoinColumn(name = "categoryId")
  private Category category;
  /**
   *list of questions in a quiz attribute.
  */
  @OneToMany(mappedBy = "subCategory", cascade = CascadeType.ALL)
  @JsonIgnore
  private List<Question> question = new ArrayList<>();
  /**
   *list of results of a quiz.
  */
  @OneToMany(mappedBy = "subCategory", cascade = CascadeType.ALL)
  @JsonIgnore
  private List<Results> results = new ArrayList<>();
}
