package com.capstone.assessmentPortal.model;

import java.util.ArrayList;
import java.util.List;

import com.capstone.assessmentPortal.response.ValidationMessage;
import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * users entity class.
 */
@Setter
@Getter
@NoArgsConstructor
@Entity
public class Users {
    /**
     * user id autogenerated attribute.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long userId;
    /**
     * first name of user attribute.
     */
    @Column
    @NotBlank(message = ValidationMessage.firstNameNotblank)
    private String firstName;
    /**
     * last name of user attribute.
     */
    @Column
    @NotBlank(message = ValidationMessage.lastNameNotblank)
    private String lastName;
    /**
     * date of birth(dd-mm-yyyy) attribute.
     */
    @Column
    @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}",
          message = ValidationMessage.dobPattern)
    @NotBlank(message = ValidationMessage.dobNotblank)
    private String dateOfBirth;
    /**
     * user gender attribute.
     */
    @Column
    @NotBlank(message = ValidationMessage.genderNotblank)
    private String gender;
    /**
     * user email attribute.
     */
    @Column(unique = true)
    @NotBlank(message = ValidationMessage.emailNotblank)
    @Pattern(regexp = "^[A-Z0-9a-z.+_-]+@nucleusteq[.]com$",
    message = ValidationMessage.emailPattern)
    private String emailId;
    /**
     * user password attribute.
     */
    @Column
    @NotBlank(message = ValidationMessage.passwordNotblank)
    @Pattern(regexp = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])"
            + "(?=.*[@#$%^&+=])(?=\\S+$).{8,}$",
            message = ValidationMessage.passwordPattern)
    private String password;
    /**
     * role of user attribute.
     */
    @Column
    private String userType = "Student";
    /**
     * list of results of user attribute.
     */
    @OneToMany(mappedBy = "students", cascade = CascadeType.ALL)
    @JsonIgnore
    private List<Results> results = new ArrayList<>();
    /**
     * get results.
     * @return results
     */
    public final List<Results> getResults() {
        return new ArrayList<>(results);
    }
    /**
     * set results.
     * @param res res
     */
    public final void setResults(final List<Results> res) {
        this.results = new ArrayList<>(res);
    }
    /**
     * parameter constructor for users.
     * @param name name
     * @param userid userid
     */
    public Users(final String name, final Long userid) {
        this.userId = userid;
        this.firstName = name;
    }
    /**
     * parameter constructor for users.
     * @param userid userid
     * @param firstname firstname
     * @param lastname lastname
     * @param dateofBirth dateofBirth
     * @param genDer genDer
     * @param emailid emailid
     */
    public Users(final Long userid, final String firstname,
            final String lastname, final String dateofBirth,
            final String genDer, final String emailid) {
        this.userId = userid;
        this.firstName = firstname;
        this.lastName = lastname;
        this.dateOfBirth = dateofBirth;
        this.gender = genDer;
        this.emailId = emailid;
    }
}
