package com.capstone.assessmentportal.dto;

import java.util.Objects;

import com.capstone.assessmentportal.response.ValidationMessage;
import com.fasterxml.jackson.annotation.JsonInclude;

import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * users Dto class for getting user details.
*/

@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserDetails {
  /**
   * user id autogenerated attribute.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long userId;
  /**
   *first name of user attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.FIRSTNAME_NOTBLANK)
  private String firstName;
  /**
   *last name of user attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.LASTNAME_NOTBLANK)
  private String lastName;
  /**
   *date of birth(dd-mm-yyyy) attribute.
 */
  @Column(nullable = false)
  @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}",
         message = ValidationMessage.DOB_PATTERN)
  @NotBlank(message = ValidationMessage.DOB_NOTBLANK)
  private String dateOfBirth;
  /**
   *user gender attribute.
 */
  @Column(nullable = false)
  @Enumerated(EnumType.STRING)
  private Gender gender;
  /**
   *user email attribute.
 */
  @Column(nullable = false)
  @NotBlank(message = ValidationMessage.EMAIL_NOTBLANK)
  @Pattern(regexp = "^[A-Z0-9a-z.+_-]+@nucleusteq[.]com$",
          message = ValidationMessage.EMAIL_PATTERN)
  private String emailId;
  /**
   *role of user attribute.
 */
  private String userType = "Student";
  /**
   *hashcode method.
  */
  @Override
  public final int hashCode() {
    return Objects.hash(dateOfBirth, emailId, firstName,
            gender, lastName, userId, userType);
  }
  /**
   *equals method.
  */
  @Override
  public final boolean equals(final Object obj) {
    if (this == obj) {
        return true;
    }
    if (obj == null) {
        return false;
    }
    if (getClass() != obj.getClass()) {
        return false;
    }
    UserDetails other = (UserDetails) obj;
    return Objects.equals(dateOfBirth, other.dateOfBirth)
            && Objects.equals(emailId, other.emailId)
            && Objects.equals(firstName, other.firstName)
            && gender == other.gender
            && Objects.equals(lastName, other.lastName)
            && Objects.equals(userId, other.userId)
            && Objects.equals(userType, other.userType);
  }
}
